import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel2 = [
  {
    key: 'aid',
    name: 'Aide',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (une bandelette de tissu blanc)',
    duration: '8 heures',
    classes: 'Clerc, Paladin',
    description: `Jusqu’à trois créatures de votre choix à portée voient leur maximum de points de vie et leurs points de vie actuels augmenter de 5 pendant la durée du sort.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 3 ou supérieur, les points de vie augmentent de 5 supplémentaires par niveau au-delà du niveau 2.`,
  },

  {
    key: 'alter-self',
    name: 'Altération d’apparence',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous modifiez votre forme physique. Vous choisissez l’un des effets suivants : Aquatique Adaptation, Change Appearance ou Natural Weapons.`,
  },

  {
    key: 'animal-messenger',
    name: 'Messager animal',
    level: 2,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (un morceau de nourriture)',
    duration: '24 heures',
    classes: 'Barde, Druide, Rôdeur',
    description: `Vous utilisez une bête Tiny à portée pour livrer un message oral à une destination que vous indiquez.`,
  },

  {
    key: 'arcane-lock',
    name: 'Verrou magique',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (poussière d’or d’une valeur de 25 po)',
    duration: 'Jusqu’à dissipation',
    classes: 'Magicien',
    description: `Vous verrouillez magiquement une porte, une fenêtre ou un coffre que vous touchez, le rendant plus difficile à forcer ou à ouvrir.`,
  },

  {
    key: 'augury',
    name: 'Augure',
    level: 2,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Personnel',
    components: 'V, S, M (bâtons marqués, os ou objets similaires)',
    duration: 'Instantanée',
    classes: 'Clerc, Druide',
    description: `Vous recevez un présage concernant les résultats possibles d’une action spécifique que vous prévoyez d’entreprendre.`,
  },

  {
    key: 'barkskin',
    name: 'Peau d’écorce',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une poignée d’écorce)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Rôdeur',
    description: `La peau de la cible devient rugueuse comme l’écorce. Tant que le sort dure, la CA de la cible ne peut pas être inférieure à 16.`,
  },

  {
    key: 'blur',
    name: 'Flou',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Votre corps devient flou, donnant Désavantage aux attaques contre vous tant que le sort dure.`,
  },

  {
    key: 'branding-smite',
    name: 'Châtiment flamboyant',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `La prochaine fois que vous touchez une créature avec une attaque d’arme, elle subit 2d6 dégâts radiants supplémentaires et devient visible si elle est invisible.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'calm-emotions',
    name: 'Apaisement des émotions',
    level: 2,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Clerc',
    description: `Vous tentez de supprimer des émotions fortes dans un groupe de créatures à portée.`,
  },

  {
    key: 'cloud-of-daggers',
    name: 'Nuée de dagues',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un éclat de verre)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous remplissez l’air de dagues tournoyantes dans un cube de 1,5 m. Toute créature qui entre dans la zone ou y commence son tour subit 4d4 dégâts tranchants.`,
    atHigherLevels: `Les dégâts augmentent de 2d4 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'continual-flame',
    name: 'Flamme éternelle',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (poussière de rubis d’une valeur de 50 po)',
    duration: 'Jusqu’à dissipation',
    classes: 'Clerc, Druide, Magicien',
    description: `Une flamme permanente apparaît sur un objet que vous touchez. Elle n’émet pas de chaleur.`,
  },

  {
    key: 'darkness',
    name: 'Ténèbres',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, M (une fourrure de chauve-souris)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Occultiste, Magicien',
    description: `Une sphère de ténèbres magiques de 4,5 m de rayon s’étend depuis un point à portée.`,
  },

  {
    key: 'darkvision',
    name: 'Vision dans le noir',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une carotte)',
    duration: '8 heures',
    classes: 'Druide, Rôdeur, Ensorceleur, Magicien',
    description: `Vous conférez la vision dans le noir à une créature consentante.`,
  },

  {
    key: 'detect-thoughts',
    name: 'Détection des pensées',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une pièce de cuivre)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Pendant la durée du sort, vous pouvez lire les pensées superficielles de certaines créatures.`,
  },

  {
    key: 'enhance-ability',
    name: 'Amélioration de caractéristique',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (poils d’animal)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Clerc, Druide, Ensorceleur',
    description: `Vous conférez un avantage magique à une créature, améliorant temporairement une caractéristique.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 3 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 2.`,
  },

  {
    key: 'find-steed',
    name: 'Monture invoquée',
    level: 2,
    school: 'Conjuration',
    castingTime: '10 minutes',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Paladin',
    description: `Vous invoquez un esprit prenant la forme d’une monture loyale.`,
  },

  {
    key: 'find-traps',
    name: 'Détection des pièges',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Druide, Rôdeur',
    description: `Vous détectez la présence de pièges dans un rayon de 36 m.`,
  },

  {
    key: 'flame-blade',
    name: 'Lame de feu',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V, S, M (une feuille de sumac)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide',
    description: `Vous invoquez une lame de feu qui inflige 3d6 dégâts de Feu lors d’une attaque de mêlée.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'flaming-sphere',
    name: 'Sphère enflammée',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (une boule de suif)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Une sphère de feu de 1,5 m de diamètre apparaît et brûle les créatures proches.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },
  {
    key: 'gentle-repose',
    name: 'Repos paisible',
    level: 2,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Toucher',
    components:
      'V, S, M (une pincée de sel et une pièce de cuivre placée sur chaque œil)',
    duration: '10 jours',
    classes: 'Barde, Clerc, Paladin',
    description: `Vous touchez un cadavre ou d’autres restes. La cible est protégée contre la décomposition et ne peut pas devenir un mort-vivant pendant la durée du sort.`,
  },

  {
    key: 'gust-of-wind',
    name: 'Rafale de vent',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel (ligne de 18 m)',
    components: 'V, S, M (une légumineuse)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Une ligne de vent fort jaillit de vous, repoussant les créatures et dispersant les gaz.`,
  },

  {
    key: 'heat-metal',
    name: 'Chaleur métallique',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un morceau de fer)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Druide',
    description: `Vous chauffez un objet métallique, infligeant 2d8 dégâts de Feu à toute créature en contact avec lui.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'hold-person',
    name: 'Immobilisation de personne',
    level: 2,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un petit morceau de fer)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Clerc, Druide, Ensorceleur, Magicien',
    description: `Choisissez un humanoïde à portée. Il doit réussir un jet de sauvegarde de Sagesse ou être Paralysé.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 3 ou supérieur, vous pouvez cibler un humanoïde supplémentaire par niveau au-delà du niveau 2.`,
  },

  {
    key: 'invisibility',
    name: 'Invisibilité',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (un cil enveloppé dans de la gomme arabique)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Une créature que vous touchez devient invisible jusqu’à la fin du sort.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 3 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 2.`,
  },

  {
    key: 'knock',
    name: 'Déverrouillage',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Un fort coup résonnant ouvre un objet verrouillé non magique ou supprime un verrou magique.`,
  },

  {
    key: 'lesser-restoration',
    name: 'Restauration partielle',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide, Paladin, Rôdeur',
    description: `Vous mettez fin à une maladie ou à une condition affectant une créature.`,
  },

  {
    key: 'levitate',
    name: 'Lévitation',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (une petite boucle de cuir)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Une créature ou un objet de taille Medium ou plus petit s’élève verticalement.`,
  },

  {
    key: 'locate-animals-or-plants',
    name: 'Localisation d’animaux ou de plantes',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un brin de fourrure)',
    duration: 'Instantanée',
    classes: 'Barde, Druide, Rôdeur',
    description: `Vous apprenez la direction et la distance de l’animal ou de la plante la plus proche correspondant à la description.`,
  },

  {
    key: 'locate-object',
    name: 'Localisation d’objet',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une brindille en forme de fourche)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Clerc, Druide, Paladin, Rôdeur',
    description: `Vous percevez la direction de l’objet le plus proche d’un type spécifique.`,
  },

  {
    key: 'magic-mouth',
    name: 'Bouche magique',
    level: 2,
    school: 'Illusion',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S, M (un rayon de miel)',
    duration: 'Jusqu’à dissipation',
    classes: 'Barde, Magicien',
    description: `Vous implantez un message audible dans un objet que vous touchez.`,
  },

  {
    key: 'magic-weapon',
    name: 'Arme magique',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action bonus',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Paladin, Rôdeur',
    description: `Une arme non magique devient magique et reçoit un bonus de +1 aux jets d’attaque et de dégâts.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 4 ou supérieur, le bonus passe à +2.`,
  },

  {
    key: 'misty-step',
    name: 'Pas brumeux',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous vous téléportez magiquement jusqu’à 9 m vers un espace inoccupé que vous pouvez voir.`,
  },

  {
    key: 'moonbeam',
    name: 'Rayon lunaire',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (plusieurs graines)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide',
    description: `Un rayon de lumière lunaire frappe une zone, infligeant 2d10 dégâts radiants.`,
    atHigherLevels: `Les dégâts augmentent de 1d10 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'pass-without-trace',
    name: 'Passage sans trace',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (cendres)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Rôdeur',
    description: `Un voile de silence et d’ombre masque vous et vos alliés, leur conférant un bonus de +10 aux tests de Dextérité (Discrétion).`,
  },

  {
    key: 'prayer-of-healing',
    name: 'Prière de guérison',
    level: 2,
    school: 'Évocation',
    castingTime: '10 minutes',
    range: '30 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Jusqu’à six créatures de votre choix à portée regagnent 2d8 + votre caractéristique d’incantation en points de vie.`,
    atHigherLevels: `Les soins augmentent de 1d8 par niveau d’emplacement au-delà du niveau 2.`,
  },
  {
    key: 'protection-from-poison',
    name: 'Protection contre le poison',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `Vous touchez une créature. Si elle est Empoisonnée, la condition prend fin. Pendant la durée du sort, la cible a Avantage aux jets de sauvegarde contre l’état Empoisonné et Résistance aux dégâts de Poison.`,
  },

  {
    key: 'ray-of-enfeeblement',
    name: 'Rayon d’affaiblissement',
    level: 2,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Occultiste, Magicien',
    description: `Faites une attaque de sort à distance contre une créature. En cas de réussite, la cible inflige seulement la moitié des dégâts avec les attaques utilisant la Force jusqu’à la fin du sort.`,
  },

  {
    key: 'rope-trick',
    name: 'Tour de corde',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une corde)',
    duration: '1 heure',
    classes: 'Magicien',
    description: `Une corde se dresse verticalement et mène à un espace extradimensionnel dissimulé.`,
  },

  {
    key: 'scorching-ray',
    name: 'Rayon ardent',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez trois rayons de feu et effectuez une attaque de sort à distance pour chacun. En cas de réussite, un rayon inflige 2d6 dégâts de Feu.`,
    atHigherLevels: `Vous créez un rayon supplémentaire pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'see-invisibility',
    name: 'Vision de l’invisible',
    level: 2,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une pincée de poudre de talc)',
    duration: '1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Pendant la durée du sort, vous voyez les créatures et objets invisibles comme s’ils étaient visibles.`,
  },

  {
    key: 'shatter',
    name: 'Fracassement',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un éclat de mica)',
    duration: 'Instantanée',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Un bruit assourdissant éclate depuis un point à portée. Les créatures dans une sphère de 3 m doivent réussir un jet de sauvegarde de Constitution ou subir 3d8 dégâts de Tonnerre.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque niveau d’emplacement au-delà du niveau 2.`,
  },

  {
    key: 'silence',
    name: 'Silence',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Clerc, Rôdeur',
    description: `Aucun son ne peut être créé à l’intérieur ou traverser une sphère de 6 m de rayon centrée sur un point à portée.`,
  },

  {
    key: 'spider-climb',
    name: 'Marche sur les murs',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une goutte de bitume)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Une créature que vous touchez peut se déplacer sur des surfaces verticales et au plafond.`,
  },

  {
    key: 'spike-growth',
    name: 'Croissance d’épines',
    level: 2,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S, M (sept épines pointues)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide, Rôdeur',
    description: `Le sol se couvre d’épines et de ronces, devenant terrain difficile et infligeant des dégâts aux créatures qui s’y déplacent.`,
  },

  {
    key: 'spiritual-weapon',
    name: 'Arme spirituelle',
    level: 2,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: '60 pieds',
    components: 'V, S',
    duration: '1 minute',
    classes: 'Clerc',
    description: `Vous créez une arme spectrale flottante qui attaque les ennemis à votre commandement.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque deux niveaux d’emplacement au-dessus du niveau 2.`,
  },

  {
    key: 'suggestion',
    name: 'Suggestion',
    level: 2,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, M (une langue de serpent)',
    duration: 'Concentration, jusqu’à 8 heures',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous suggérez une ligne de conduite raisonnable à une créature à portée. Elle doit réussir un jet de sauvegarde de Sagesse ou suivre la suggestion.`,
  },

  {
    key: 'warding-bond',
    name: 'Lien de protection',
    level: 2,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une paire d’anneaux de platine)',
    duration: '1 heure',
    classes: 'Clerc, Paladin',
    description: `Vous créez un lien protecteur entre vous et une créature consentante.`,
  },

  {
    key: 'web',
    name: 'Toile',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un peu de toile d’araignée)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous invoquez une masse de toiles collantes qui entravent les créatures.`,
  },
];

export async function seedSpellsLevel2(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 2...');

  for (const data of srdSpellsLevel2) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
