import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel8 = [
  {
    key: 'animal-shapes',
    name: 'Formes animales',
    level: 8,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 24 heures',
    classes: 'Druide',
    description: `Vous transformez un nombre quelconque de créatures consentantes en bêtes.`,
  },

  {
    key: 'antimagic-field',
    name: 'Champ antimagie',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel (rayon de 3 m)',
    components: 'V, S, M (un fragment de fer pur)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Clerc, Magicien',
    description: `Une sphère d’antimagie vous entoure et supprime la magie dans son rayon.`,
  },

  {
    key: 'antipathy-sympathy',
    name: 'Antipathie/Sympathie',
    level: 8,
    school: 'Enchantement',
    castingTime: '1 heure',
    range: '60 pieds',
    components: 'V, S, M (un morceau de fer et un morceau de bois)',
    duration: '10 jours',
    classes: 'Druide, Magicien',
    description: `Vous imprégnez un objet ou une zone d’une aura attirant ou repoussant certaines créatures.`,
  },

  {
    key: 'befuddlement',
    name: 'Confusion profonde',
    level: 8,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous submergez l’esprit de la cible, la rendant incapable de réagir correctement.`,
  },

  {
    key: 'clone',
    name: 'Clone',
    level: 8,
    school: 'Nécromancie',
    castingTime: '1 heure',
    range: 'Toucher',
    components: 'V, S, M (un récipient scellé d’une valeur de 2 000 po)',
    duration: 'Instantanée',
    classes: 'Magicien',
    description: `Vous créez un double inactif d’une créature, prêt à recevoir son âme à sa mort.`,
  },

  {
    key: 'control-weather',
    name: 'Contrôle du climat',
    level: 8,
    school: 'Transmutation',
    castingTime: '10 minutes',
    range: 'Personnel',
    components: 'V, S, M (encens brûlant)',
    duration: 'Concentration, jusqu’à 8 heures',
    classes: 'Druide',
    description: `Vous modifiez progressivement les conditions météorologiques dans une vaste zone.`,
  },

  {
    key: 'demiplane',
    name: 'Demi-plan',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'S',
    duration: '1 heure',
    classes: 'Magicien',
    description: `Vous créez une porte menant à un demi-plan personnel.`,
  },

  {
    key: 'dominate-monster',
    name: 'Domination de monstre',
    level: 8,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous prenez le contrôle de l’esprit d’une créature.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 9, la durée devient permanente.`,
  },

  {
    key: 'earthquake',
    name: 'Séisme',
    level: 8,
    school: 'Évocation',
    castingTime: '1 action',
    range: '500 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Druide',
    description: `Le sol tremble violemment, détruisant structures et renversant les créatures.`,
  },
  {
    key: 'glibness',
    name: 'Bagout suprême',
    level: 8,
    school: 'Enchantement',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: '1 heure',
    classes: 'Barde',
    description: `Vos mensonges deviennent presque impossibles à détecter et votre éloquence atteint un niveau surnaturel.`,
  },

  {
    key: 'holy-aura',
    name: 'Aura sacrée',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un reliquaire sacré)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc',
    description: `Une lumière divine protège les créatures alliées proches et punit les ennemis.`,
  },

  {
    key: 'incendiary-cloud',
    name: 'Nuage incendiaire',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Un nuage de fumées brûlantes inflige des dégâts de feu persistants.`,
  },

  {
    key: 'maze',
    name: 'Labyrinthe',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Vous bannissez une créature dans un labyrinthe extradimensionnel.`,
  },

  {
    key: 'mind-blank',
    name: 'Esprit impénétrable',
    level: 8,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: '24 heures',
    classes: 'Barde, Magicien',
    description: `La cible est protégée contre les effets mentaux et la détection magique.`,
  },

  {
    key: 'power-word-stun',
    name: 'Mot de pouvoir : étourdissement',
    level: 8,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous prononcez un mot de pouvoir qui étourdit une créature affaiblie.`,
  },

  {
    key: 'sunburst',
    name: 'Explosion solaire',
    level: 8,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S, M (un fragment de soleil)',
    duration: 'Instantanée',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Une explosion de lumière solaire inflige des dégâts radiants et aveugle les créatures.`,
  },

  {
    key: 'tsunami',
    name: 'Tsunami',
    level: 8,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Vue',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 6 rounds',
    classes: 'Druide',
    description: `Une vague colossale se déplace et ravage tout sur son passage.`,
  },
];

export async function seedSpellsLevel8(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 8...');

  for (const data of srdSpellsLevel8) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
