import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel9 = [
  {
    key: 'astral-projection',
    name: 'Projection astrale',
    level: 9,
    school: 'Nécromancie',
    castingTime: '1 heure',
    range: '10 pieds',
    components:
      'V, S, M (un bâtonnet d’argent d’une valeur de 1 000 po, consommé)',
    duration: 'Spéciale',
    classes: 'Clerc, Druide, Magicien',
    description: `Vous projetez votre corps astral et celui de créatures consentantes sur le plan Astral.`,
    atHigherLevels: undefined,
  },

  {
    key: 'foresight',
    name: 'Prescience',
    level: 9,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Toucher',
    components: 'V, S, M (une plume de colibri)',
    duration: '8 heures',
    classes: 'Barde, Druide, Magicien',
    description: `La cible bénéficie d’un sixième sens surnaturel, lui conférant un avantage constant.`,
  },

  {
    key: 'gate',
    name: 'Portail',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un diamant d’une valeur de 5 000 po)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Ensorceleur, Magicien',
    description: `Vous ouvrez un portail reliant deux plans d’existence.`,
  },

  {
    key: 'imprisonment',
    name: 'Emprisonnement',
    level: 9,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S, M (un joyau d’une valeur de 500 po par DV de la cible)',
    duration: 'Jusqu’à dissipation',
    classes: 'Ensorceleur, Magicien',
    description: `Vous enfermez une créature dans une prison magique durable.`,
  },

  {
    key: 'mass-heal',
    name: 'Soins de masse',
    level: 9,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous restaurez instantanément un très grand nombre de points de vie à plusieurs créatures.`,
  },

  {
    key: 'meteor-swarm',
    name: 'Essaim de météores',
    level: 9,
    school: 'Évocation',
    castingTime: '1 action',
    range: '1 mile',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Des météores flamboyants s’abattent sur une vaste zone, provoquant une destruction massive.`,
  },

  {
    key: 'power-word-heal',
    name: 'Mot de pouvoir : guérison',
    level: 9,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Clerc',
    description: `Un mot de pouvoir restaure immédiatement tous les points de vie de la cible.`,
  },

  {
    key: 'power-word-kill',
    name: 'Mot de pouvoir : mort',
    level: 9,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous prononcez un mot de pouvoir qui tue instantanément une créature affaiblie.`,
  },
  {
    key: 'prismatic-wall',
    name: 'Mur prismatique',
    level: 9,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: '10 minutes',
    classes: 'Magicien',
    description: `Un mur de lumière multicolore apparaît, chaque couche ayant un effet destructeur différent.`,
  },

  {
    key: 'shapechange',
    name: 'Changement de forme',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un diadème de jade)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Magicien',
    description: `Vous adoptez la forme de n’importe quelle créature.`,
  },

  {
    key: 'storm-of-vengeance',
    name: 'Tempête de vengeance',
    level: 9,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Vue',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide',
    description: `Vous invoquez une tempête apocalyptique qui ravage une vaste zone.`,
  },

  {
    key: 'time-stop',
    name: 'Arrêt du temps',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Magicien',
    description: `Vous stoppez brièvement le temps pour toutes les créatures sauf vous.`,
  },

  {
    key: 'true-polymorph',
    name: 'Véritable métamorphose',
    level: 9,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (une goutte de mercure)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Druide, Magicien',
    description: `Vous transformez définitivement une créature ou un objet.`,
  },

  {
    key: 'true-resurrection',
    name: 'Résurrection suprême',
    level: 9,
    school: 'Nécromancie',
    castingTime: '1 heure',
    range: 'Toucher',
    components: 'V, S, M (un diamant d’une valeur de 25 000 po, consommé)',
    duration: 'Instantanée',
    classes: 'Clerc, Druide',
    description: `Vous ramenez à la vie une créature morte depuis très longtemps, même sans corps.`,
  },

  {
    key: 'weird',
    name: 'Vision cauchemardesque',
    level: 9,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous plongez les créatures dans des visions terrifiantes issues de leurs pires cauchemars.`,
  },

  {
    key: 'wish',
    name: 'Souhait',
    level: 9,
    school: 'Invocation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous altérez la réalité elle-même en formulant un souhait d’une puissance inégalée.`,
  },
];

export async function seedSpellsLevel9(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 9...');

  for (const data of srdSpellsLevel9) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
