import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel6 = [
  {
    key: 'blade-barrier',
    name: 'Barrière de lames',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc',
    description: `Vous créez un mur tourbillonnant de lames tranchantes qui inflige des dégâts aux créatures qui le traversent.`,
  },

  {
    key: 'chain-lightning',
    name: 'Chaîne d’éclairs',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S, M (un fragment de fourrure)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un éclair frappe une créature puis se propage à d’autres cibles proches.`,
  },

  {
    key: 'circle-of-death',
    name: 'Cercle de mort',
    level: 6,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S, M (une perle noire)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Une sphère d’énergie nécromantique inflige de lourds dégâts aux créatures dans une vaste zone.`,
  },

  {
    key: 'conjure-fey',
    name: 'Invocation de fée',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Occultiste',
    description: `Vous invoquez une créature féerique puissante qui obéit à vos ordres.`,
  },

  {
    key: 'contingency',
    name: 'Contingence',
    level: 6,
    school: 'Abjuration',
    castingTime: '10 minutes',
    range: 'Personnel',
    components: 'V, S, M (une statuette de vous-même)',
    duration: '10 jours',
    classes: 'Magicien',
    description: `Vous préparez un sort qui se déclenchera automatiquement sous certaines conditions.`,
  },

  {
    key: 'create-undead',
    name: 'Création de morts-vivants',
    level: 6,
    school: 'Nécromancie',
    castingTime: '1 minute',
    range: '10 pieds',
    components: 'V, S, M (un onyx d’une valeur minimale)',
    duration: 'Instantanée',
    classes: 'Clerc, Occultiste',
    description: `Vous transformez des cadavres en morts-vivants sous votre contrôle.`,
    atHigherLevels: `Vous pouvez créer davantage de morts-vivants lorsque vous utilisez des emplacements de sort de niveau supérieur.`,
  },

  {
    key: 'disintegrate',
    name: 'Désintégration',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un aimant et une pincée de poussière)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un rayon vert réduit la cible et les objets à l’état de poussière.`,
  },

  {
    key: 'drawmij-s-instant-summons',
    name: 'Invocation instantanée de Drawmij',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 minute rituel',
    range: 'Toucher',
    components: 'V, S, M (un saphir d’une valeur de 1 000 po)',
    duration: 'Jusqu’à dissipation',
    classes: 'Magicien',
    description: `Vous liez un objet à un joyau afin de pouvoir l’invoquer instantanément.`,
  },

  {
    key: 'eyebite',
    name: 'Morsure oculaire',
    level: 6,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Votre regard inflige des effets terrifiants ou affaiblissants aux créatures.`,
  },

  {
    key: 'find-the-path',
    name: 'Trouver le chemin',
    level: 6,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Personnel',
    components: 'V, S, M (un ensemble d’outils de divination)',
    duration: 'Concentration, jusqu’à 1 jour',
    classes: 'Barde, Clerc, Druide',
    description: `Vous percevez le chemin le plus court vers un lieu précis.`,
  },

  {
    key: 'flesh-to-stone',
    name: 'Pétrification',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (une pincée de chaux)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous tentez de transformer une créature en pierre.`,
  },
  {
    key: 'forbiddance',
    name: 'Interdiction',
    level: 6,
    school: 'Abjuration',
    castingTime: '10 minutes rituel',
    range: 'Toucher',
    components: 'V, S, M (de l’eau bénite ou profane)',
    duration: '1 jour',
    classes: 'Clerc',
    description: `Vous protégez une zone contre les intrusions extraplanaires et les types de créatures que vous choisissez.`,
  },

  {
    key: 'globe-of-invulnerability',
    name: 'Globe d’invulnérabilité',
    level: 6,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel (rayon de 3 m)',
    components: 'V, S, M (une perle de verre)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Un champ magique vous entoure et bloque les sorts de faible niveau.`,
  },

  {
    key: 'guards-and-wards',
    name: 'Gardiens et protections',
    level: 6,
    school: 'Abjuration',
    castingTime: '10 minutes',
    range: 'Toucher',
    components: 'V, S, M (encens, huile et argent)',
    duration: '24 heures',
    classes: 'Barde, Magicien',
    description: `Vous protégez un bâtiment avec des effets magiques durables.`,
  },

  {
    key: 'harm',
    name: 'Fléau',
    level: 6,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous infligez de lourds dégâts nécrotiques et réduisez temporairement le maximum de points de vie de la cible.`,
  },

  {
    key: 'heal',
    name: 'Guérison',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Druide',
    description: `Vous restaurez instantanément un grand nombre de points de vie à une créature.`,
  },

  {
    key: 'heroes-feast',
    name: 'Festin des héros',
    level: 6,
    school: 'Conjuration',
    castingTime: '10 minutes',
    range: '30 pieds',
    components: 'V, S, M (un bol orné d’une valeur de 1 000 po, consommé)',
    duration: 'Instantanée',
    classes: 'Clerc, Druide',
    description: `Vous invoquez un grand festin qui renforce les créatures qui y participent.`,
  },

  {
    key: 'magic-jar',
    name: 'Jar magique',
    level: 6,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un récipient précieux)',
    duration: 'Jusqu’à dissipation',
    classes: 'Ensorceleur, Magicien',
    description: `Votre âme quitte votre corps pour posséder d’autres créatures.`,
  },

  {
    key: 'mass-suggestion',
    name: 'Suggestion de masse',
    level: 6,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, M (une langue de serpent)',
    duration: '24 heures',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous influencez l’esprit de plusieurs créatures simultanément.`,
  },

  {
    key: 'move-earth',
    name: 'Déplacement de terre',
    level: 6,
    school: 'Transmutation',
    castingTime: '10 minutes',
    range: '120 pieds',
    components: 'V, S, M (une pelle miniature)',
    duration: 'Concentration, jusqu’à 2 heures',
    classes: 'Druide, Magicien',
    description: `Vous façonnez et déplacez de grandes quantités de terre.`,
  },

  {
    key: 'otiluke-s-freezing-sphere',
    name: 'Sphère glaciale d’Otiluke',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: '300 pieds',
    components: 'V, S, M (une sphère de cristal)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Une sphère de froid intense explose et inflige des dégâts de froid.`,
  },
  {
    key: 'otto-s-irresistible-dance',
    name: 'Danse irrésistible d’Otto',
    level: 6,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Une créature que vous voyez commence à danser de façon incontrôlable.`,
  },

  {
    key: 'planar-ally',
    name: 'Allié planaire',
    level: 6,
    school: 'Conjuration',
    castingTime: '10 minutes',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous sollicitez l’aide d’un être extraplanaire qui peut accomplir une tâche pour vous.`,
  },

  {
    key: 'programmed-illusion',
    name: 'Illusion programmée',
    level: 6,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un fragment de jade)',
    duration: 'Jusqu’à dissipation',
    classes: 'Barde, Magicien',
    description: `Vous créez une illusion complexe qui se déclenche selon des conditions prédéfinies.`,
  },

  {
    key: 'sunbeam',
    name: 'Rayon de soleil',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un symbole sacré)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Druide',
    description: `Un rayon de lumière solaire jaillit de vous, infligeant des dégâts radiants et aveuglant les créatures.`,
  },

  {
    key: 'transport-via-plants',
    name: 'Transport végétal',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: '1 round',
    classes: 'Druide',
    description: `Vous vous déplacez instantanément entre des plantes de grande taille.`,
  },

  {
    key: 'true-seeing',
    name: 'Vision suprême',
    level: 6,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (un onguent spécial)',
    duration: '1 heure',
    classes: 'Barde, Clerc, Druide, Magicien',
    description: `La cible voit la réalité telle qu’elle est, perçant les illusions et les métamorphoses.`,
  },

  {
    key: 'wall-of-ice',
    name: 'Mur de glace',
    level: 6,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un morceau de cristal)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Un mur de glace surgit et inflige des dégâts de froid.`,
  },

  {
    key: 'wall-of-thorns',
    name: 'Mur d’épines',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide',
    description: `Un mur d’épines entrave et blesse les créatures qui le traversent.`,
  },

  {
    key: 'wind-walk',
    name: 'Marche du vent',
    level: 6,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S',
    duration: '8 heures',
    classes: 'Druide',
    description: `Vous et vos alliés vous transformez en formes gazeuses rapides.`,
  },

  {
    key: 'word-of-recall',
    name: 'Mot de rappel',
    level: 6,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous et vos alliés êtes instantanément transportés vers un sanctuaire désigné.`,
  },
];

export async function seedSpellsLevel6(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 6...');

  for (const data of srdSpellsLevel6) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
