import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel4 = [
  {
    key: 'arcane-eye',
    name: 'Œil magique',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (un peu de poudre d’œil de chauve-souris)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Magicien',
    description: `Vous créez un œil magique invisible qui flotte et se déplace selon votre volonté, vous transmettant ce qu’il voit.`,
  },

  {
    key: 'banishment',
    name: 'Bannissement',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un objet détesté par la cible)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous tentez de bannir une créature vers un autre plan d’existence.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 5 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 4.`,
  },

  {
    key: 'blight',
    name: 'Flétrissement',
    level: 4,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Druide',
    description: `La vitalité d’une plante ou d’une créature végétale est drainée, infligeant 8d8 dégâts nécrotiques.`,
  },

  {
    key: 'blightful-curse',
    name: 'Malédiction funeste',
    level: 4,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Occultiste',
    description: `Vous infligez une malédiction qui affaiblit progressivement la cible.`,
  },

  {
    key: 'blightstorm',
    name: 'Tempête de flétrissement',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Druide',
    description: `Une tempête de magie corruptrice inflige des dégâts nécrotiques aux créatures dans la zone.`,
  },

  {
    key: 'blizzard',
    name: 'Blizzard',
    level: 4,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Une tempête de neige magique s’abat sur une large zone.`,
  },

  {
    key: 'blightwind',
    name: 'Vent de corruption',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Druide',
    description: `Un vent chargé de magie corruptrice balaie la zone.`,
  },

  {
    key: 'confusion',
    name: 'Confusion',
    level: 4,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S, M (trois coquilles de noix)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous semez la confusion dans l’esprit des créatures dans une zone.`,
  },

  {
    key: 'conjure-minor-elementals',
    name: 'Invocation d’élémentaires mineurs',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Magicien',
    description: `Vous invoquez des esprits élémentaires prenant forme physique.`,
  },

  {
    key: 'control-water',
    name: 'Contrôle de l’eau',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '300 pieds',
    components: 'V, S, M (une goutte d’eau)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc, Druide',
    description: `Vous contrôlez le mouvement et la forme de l’eau dans une vaste zone.`,
  },

  {
    key: 'death-ward',
    name: 'Protection contre la mort',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: '8 heures',
    classes: 'Clerc, Paladin',
    description: `La première fois que la cible tomberait à 0 point de vie, elle tombe à 1 point de vie à la place.`,
  },

  {
    key: 'dimension-door',
    name: 'Porte dimensionnelle',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '500 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous vous téléportez, vous et éventuellement une créature consentante, vers un endroit que vous visualisez.`,
  },
  {
    key: 'divination',
    name: 'Divination',
    level: 4,
    school: 'Divination',
    castingTime: '1 action rituel',
    range: 'Personnel',
    components: 'V, S, M (encens et une offrande sacrificielle)',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous communiez avec une divinité ou un serviteur divin et recevez un présage concernant les événements à venir.`,
  },

  {
    key: 'dominate-beast',
    name: 'Domination de bête',
    level: 4,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur',
    description: `Vous tentez de soumettre une bête à votre volonté.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 5 ou supérieur, la durée augmente.`,
  },

  {
    key: 'evard-s-black-tentacles',
    name: 'Tentacules noirs d’Evard',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S, M (un morceau de tentacule)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Magicien',
    description: `Des tentacules de ténèbres surgissent du sol et entravent les créatures dans la zone.`,
  },

  {
    key: 'fabricate',
    name: 'Fabrication',
    level: 4,
    school: 'Transmutation',
    castingTime: '10 minutes',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Magicien',
    description: `Vous transformez des matières premières en objets manufacturés.`,
  },

  {
    key: 'fire-shield',
    name: 'Bouclier de feu',
    level: 4,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un morceau de phosphore)',
    duration: '10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Des flammes ou du givre protègent votre corps et blessent les attaquants.`,
  },

  {
    key: 'freedom-of-movement',
    name: 'Liberté de mouvement',
    level: 4,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une lanière de cuir)',
    duration: '1 heure',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `La cible n’est pas entravée par le terrain difficile ou les effets de paralysie.`,
  },

  {
    key: 'giant-insect',
    name: 'Insecte géant',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide',
    description: `Vous transformez des insectes ordinaires en versions gigantesques et obéissantes.`,
  },

  {
    key: 'greater-invisibility',
    name: 'Invisibilité supérieure',
    level: 4,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Une créature devient invisible même lorsqu’elle attaque ou lance des sorts.`,
  },

  {
    key: 'guardian-of-faith',
    name: 'Gardien de la foi',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V',
    duration: '8 heures',
    classes: 'Clerc',
    description: `Un gardien spectral apparaît et attaque les ennemis qui s’approchent.`,
  },

  {
    key: 'hallucinatory-terrain',
    name: 'Terrain hallucinatoire',
    level: 4,
    school: 'Illusion',
    castingTime: '10 minutes',
    range: '300 pieds',
    components: 'V, S, M (une pierre)',
    duration: '24 heures',
    classes: 'Barde, Druide, Magicien',
    description: `Vous modifiez l’apparence naturelle du terrain dans une large zone.`,
  },

  {
    key: 'ice-storm',
    name: 'Tempête de grêle',
    level: 4,
    school: 'Évocation',
    castingTime: '1 action',
    range: '300 pieds',
    components: 'V, S, M (un petit caillou)',
    duration: 'Instantanée',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Une pluie de grêle inflige des dégâts de froid et de contondant dans une zone.`,
    atHigherLevels: `Les dégâts de contondant augmentent avec les emplacements supérieurs.`,
  },

  {
    key: 'leomund-s-secret-chest',
    name: 'Coffre secret de Léomund',
    level: 4,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (un coffre précieux)',
    duration: '60 jours',
    classes: 'Magicien',
    description: `Vous dissimulez un coffre sur le plan Éthéré et pouvez le rappeler temporairement.`,
  },
  {
    key: 'locate-creature',
    name: 'Localiser une créature',
    level: 4,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un poil de sanglier)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Clerc, Druide, Paladin, Rôdeur',
    description: `Vous percevez la direction d’une créature spécifique tant qu’elle se trouve dans un rayon de 300 m.`,
  },

  {
    key: 'polymorph',
    name: 'Métamorphose',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un cocon de chenille)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Druide, Ensorceleur, Magicien',
    description: `Vous transformez une créature en une bête.`,
  },

  {
    key: 'stone-shape',
    name: 'Façonner la pierre',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (argile malléable)',
    duration: 'Instantanée',
    classes: 'Clerc, Druide, Magicien',
    description: `Vous façonnez une section de pierre en lui donnant la forme souhaitée.`,
  },

  {
    key: 'stoneskin',
    name: 'Peau de pierre',
    level: 4,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components:
      'V, S, M (poussière de diamant d’une valeur de 100 po, consommée)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Rôdeur, Ensorceleur, Magicien',
    description: `La cible obtient une résistance aux dégâts contondants, perforants et tranchants.`,
  },

  {
    key: 'wall-of-fire',
    name: 'Mur de feu',
    level: 4,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un morceau de phosphore)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Un mur de flammes apparaît et inflige des dégâts de feu.`,
    atHigherLevels: `Les dégâts augmentent lorsque vous utilisez un emplacement de sort de niveau supérieur.`,
  },
];

export async function seedSpellsLevel4(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 4...');

  for (const data of srdSpellsLevel4) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
