import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel7 = [
  {
    key: 'conjure-celestial',
    name: 'Invocation de céleste',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Clerc',
    description: `Vous invoquez un céleste puissant qui vous aide et obéit à vos ordres.`,
    atHigherLevels: undefined,
  },

  {
    key: 'delayed-blast-fireball',
    name: 'Boule de feu à retardement',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components:
      'V, S, M (une petite boule de guano de chauve-souris et de soufre)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez une boule de feu qui gagne en puissance avant d’exploser.`,
  },

  {
    key: 'divine-word',
    name: 'Parole divine',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: '30 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous prononcez une parole divine qui affecte les créatures hostiles proches.`,
  },

  {
    key: 'etherealness',
    name: 'Éthéréité',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Jusqu’à 8 heures',
    classes: 'Barde, Clerc, Ensorceleur, Magicien',
    description: `Vous passez sur le plan Éthéré et pouvez vous déplacer librement.`,
  },

  {
    key: 'finger-of-death',
    name: 'Doigt de mort',
    level: 7,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous projetez une énergie mortelle qui inflige de lourds dégâts nécrotiques.`,
  },

  {
    key: 'fire-storm',
    name: 'Tempête de feu',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Druide',
    description: `Des flammes dévastatrices surgissent en plusieurs colonnes dans la zone.`,
  },

  {
    key: 'forcecage',
    name: 'Cage de force',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action',
    range: '100 pieds',
    components: 'V, S, M (poussière de rubis)',
    duration: '1 heure',
    classes: 'Magicien',
    description: `Vous enfermez une créature ou un groupe dans une prison de force magique.`,
  },

  {
    key: 'mirage-arcane',
    name: 'Mirage arcanique',
    level: 7,
    school: 'Illusion',
    castingTime: '10 minutes',
    range: 'Vue',
    components: 'V, S',
    duration: '10 jours',
    classes: 'Barde, Druide, Magicien',
    description: `Vous transformez l’apparence et la nature d’un vaste terrain.`,
  },

  {
    key: 'mordenkainen-s-magnificent-mansion',
    name: 'Manoir somptueux de Mordenkainen',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '300 pieds',
    components: 'V, S, M (une petite porte en ivoire)',
    duration: '24 heures',
    classes: 'Barde, Magicien',
    description: `Vous créez une demeure extradimensionnelle luxueuse et sûre.`,
  },

  {
    key: 'mordenkainen-s-sword',
    name: 'Épée de Mordenkainen',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (une épée miniature en platine)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Magicien',
    description: `Vous invoquez une épée de force magique qui attaque vos ennemis.`,
  },
  {
    key: 'plane-shift',
    name: 'Changement de plan',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une fourche d’accordage en métal)',
    duration: 'Instantanée',
    classes: 'Clerc, Druide, Magicien',
    description: `Vous transportez une créature consentante ou vous-même vers un autre plan d’existence.`,
  },

  {
    key: 'prismatic-spray',
    name: 'Jet prismatique',
    level: 7,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel (cône de 18 m)',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un cône de rayons multicolores jaillit de vous, chaque rayon ayant un effet différent.`,
  },

  {
    key: 'project-image',
    name: 'Projection d’image',
    level: 7,
    school: 'Illusion',
    castingTime: '1 action',
    range: '500 miles',
    components: 'V, S, M (un petit double de vous-même)',
    duration: 'Concentration, jusqu’à 1 jour',
    classes: 'Barde, Magicien',
    description: `Vous créez une image illusoire de vous-même à très grande distance.`,
  },

  {
    key: 'regenerate',
    name: 'Régénération',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 minute',
    range: 'Toucher',
    components: 'V, S, M (un fragment de membre)',
    duration: '1 heure',
    classes: 'Barde, Clerc, Druide',
    description: `La cible récupère des points de vie et peut régénérer des membres perdus.`,
  },

  {
    key: 'resurrection',
    name: 'Résurrection',
    level: 7,
    school: 'Nécromancie',
    castingTime: '1 heure',
    range: 'Toucher',
    components: 'V, S, M (un diamant d’une valeur de 1 000 po, consommé)',
    duration: 'Instantanée',
    classes: 'Barde, Clerc',
    description: `Vous ramenez à la vie une créature morte depuis longtemps.`,
  },

  {
    key: 'reverse-gravity',
    name: 'Inversion de la gravité',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '100 pieds',
    components: 'V, S, M (un aimant)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Vous inversez la gravité dans une vaste zone.`,
  },

  {
    key: 'sequester',
    name: 'Séquestration',
    level: 7,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une poudre rare)',
    duration: 'Jusqu’à dissipation',
    classes: 'Magicien',
    description: `Vous cachez une créature ou un objet hors du temps et de la perception.`,
  },

  {
    key: 'simulacrum',
    name: 'Simulacre',
    level: 7,
    school: 'Illusion',
    castingTime: '12 heures',
    range: 'Toucher',
    components: 'V, S, M (neige ou glace)',
    duration: 'Jusqu’à dissipation',
    classes: 'Magicien',
    description: `Vous créez un double illusoire partiellement réel d’une créature.`,
  },

  {
    key: 'symbol',
    name: 'Symbole',
    level: 7,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: 'Toucher',
    components:
      'V, S, M (mercure et opale d’une valeur de 1 000 po, consommés)',
    duration: 'Jusqu’à dissipation',
    classes: 'Barde, Clerc, Magicien',
    description: `Vous inscrivez un glyphe puissant qui déclenche un effet magique dévastateur.`,
  },

  {
    key: 'teleport',
    name: 'Téléportation',
    level: 7,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '10 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous transportez instantanément des créatures vers un lieu connu.`,
  },
];

export async function seedSpellsLevel7(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 7...');

  for (const data of srdSpellsLevel7) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
