import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel5 = [
  {
    key: 'animate-objects',
    name: 'Animation d’objets',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous animez jusqu’à dix objets non magiques à portée. Chaque objet devient une créature animée sous votre contrôle.`,
  },

  {
    key: 'antilife-shell',
    name: 'Coquille antivie',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide',
    description: `Une barrière invisible vous entoure et empêche les créatures vivantes d’entrer dans son périmètre.`,
  },

  {
    key: 'awaken',
    name: 'Éveil',
    level: 5,
    school: 'Transmutation',
    castingTime: '8 heures',
    range: 'Toucher',
    components: 'V, S, M (une agate d’une valeur de 1 000 po, consommée)',
    duration: 'Instantanée',
    classes: 'Barde, Druide',
    description: `Vous conférez une conscience et une intelligence accrues à une bête ou une plante.`,
  },

  {
    key: 'bigby-s-hand',
    name: 'Main de Bigby',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (une coquille d’œuf)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez une grande main magique capable de frapper, pousser ou protéger selon votre volonté.`,
  },

  {
    key: 'cloudkill',
    name: 'Nuage mortel',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez un nuage de poison mortel qui se déplace et inflige des dégâts aux créatures à l’intérieur.`,
  },

  {
    key: 'commune',
    name: 'Communion',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute rituel',
    range: 'Personnel',
    components: 'V, S, M (encens et un symbole sacré)',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Vous contactez votre divinité et pouvez lui poser jusqu’à trois questions.`,
  },

  {
    key: 'commune-with-nature',
    name: 'Communion avec la nature',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute rituel',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Druide, Rôdeur',
    description: `Vous devenez un avec la nature et apprenez des informations sur le terrain environnant.`,
  },

  {
    key: 'cone-of-cold',
    name: 'Cône de froid',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel (cône de 18 m)',
    components: 'V, S, M (un petit cristal)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un souffle de froid extrême jaillit de vous, infligeant 8d8 dégâts de Froid aux créatures dans la zone.`,
  },

  {
    key: 'conjure-elemental',
    name: 'Invocation d’élémentaire',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '90 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Magicien',
    description: `Vous invoquez un élémentaire qui obéit à vos ordres.`,
  },

  {
    key: 'contact-other-plane',
    name: 'Contact avec un autre plan',
    level: 5,
    school: 'Divination',
    castingTime: '1 minute rituel',
    range: 'Personnel',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous contactez une entité extraplanaire et lui posez des questions, au risque de subir des effets mentaux.`,
  },

  {
    key: 'contagion',
    name: 'Contagion',
    level: 5,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Jusqu’à dissipation',
    classes: 'Clerc, Druide',
    description: `Vous affligez une créature d’une maladie magique grave.`,
  },

  {
    key: 'creation',
    name: 'Création',
    level: 5,
    school: 'Illusion',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S, M (un minuscule morceau de la matière créée)',
    duration: 'Variable',
    classes: 'Magicien',
    description: `Vous créez un objet non magique à partir d’ombre et de magie.`,
  },

  {
    key: 'dispel-evil-and-good',
    name: 'Dissipation du bien et du mal',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Paladin',
    description: `Vous êtes protégé contre certains types de créatures extraplanaires et pouvez les repousser.`,
  },
  {
    key: 'dominate-person',
    name: 'Domination de personne',
    level: 5,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous tentez de soumettre un humanoïde à votre volonté.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 6 ou supérieur, la durée augmente.`,
  },

  {
    key: 'dream',
    name: 'Rêve',
    level: 5,
    school: 'Illusion',
    castingTime: '1 minute',
    range: 'Spéciale',
    components: 'V, S, M (une poignée de sable)',
    duration: '8 heures',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous façonnez les rêves d’une créature connue.`,
  },

  {
    key: 'flame-strike',
    name: 'Colonne de flammes',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (soufre)',
    duration: 'Instantanée',
    classes: 'Clerc',
    description: `Une colonne de feu divin frappe une zone et inflige des dégâts de feu et radiants.`,
  },

  {
    key: 'geas',
    name: 'Géôas',
    level: 5,
    school: 'Enchantement',
    castingTime: '1 minute',
    range: '60 pieds',
    components: 'V',
    duration: '30 jours',
    classes: 'Barde, Clerc, Druide, Paladin',
    description: `Vous imposez un ordre magique à une créature.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 6 ou supérieur, la durée devient plus longue.`,
  },

  {
    key: 'greater-restoration',
    name: 'Restauration suprême',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components:
      'V, S, M (poussière de diamant d’une valeur de 100 po, consommée)',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide, Paladin',
    description: `Vous mettez fin à de puissants effets négatifs affectant une créature.`,
  },

  {
    key: 'hallow',
    name: 'Consécration',
    level: 5,
    school: 'Évocation',
    castingTime: '24 heures',
    range: 'Toucher',
    components: 'V, S, M (herbes, huiles et encens d’une valeur de 1 000 po)',
    duration: 'Jusqu’à dissipation',
    classes: 'Clerc',
    description: `Vous imprégnez une zone de puissance divine durable.`,
  },

  {
    key: 'hold-monster',
    name: 'Immobilisation de monstre',
    level: 5,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S, M (un petit morceau de fer)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous paralysez une créature à portée.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 6 ou supérieur, vous pouvez cibler une créature supplémentaire.`,
  },

  {
    key: 'insect-plague',
    name: 'Nuée d’insectes',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '300 pieds',
    components: 'V, S, M (quelques insectes)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc, Druide',
    description: `Une nuée d’insectes voraces ravage une zone.`,
  },

  {
    key: 'legend-lore',
    name: 'Savoir légendaire',
    level: 5,
    school: 'Divination',
    castingTime: '10 minutes',
    range: 'Personnel',
    components: 'V, S, M (encens d’une valeur de 250 po)',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Magicien',
    description: `Vous apprenez des informations légendaires sur une personne, un lieu ou un objet.`,
  },

  {
    key: 'mass-cure-wounds',
    name: 'Soins de groupe',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide',
    description: `Jusqu’à six créatures de votre choix regagnent 3d8 + votre caractéristique d’incantation en points de vie.`,
    atHigherLevels: `Les soins augmentent de 1d8 par niveau d’emplacement au-delà du niveau 5.`,
  },

  {
    key: 'mislead',
    name: 'Leurre',
    level: 5,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous devenez invisible et créez un double illusoire.`,
  },

  {
    key: 'modify-memory',
    name: 'Modification de mémoire',
    level: 5,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous altérez les souvenirs d’une créature.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 6 ou supérieur, vous pouvez modifier des souvenirs plus anciens.`,
  },

  {
    key: 'passwall',
    name: 'Passe-muraille',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez un passage temporaire à travers une surface solide.`,
  },
  {
    key: 'planar-binding',
    name: 'Lien planaire',
    level: 5,
    school: 'Abjuration',
    castingTime: '1 heure',
    range: '60 pieds',
    components: 'V, S, M (un joyau d’une valeur d’au moins 1 000 po, consommé)',
    duration: '24 heures',
    classes: 'Clerc, Druide, Magicien',
    description: `Vous liez magiquement une créature extraplanaire à votre service.`,
    atHigherLevels: `La durée augmente lorsque vous utilisez un emplacement de sort de niveau supérieur.`,
  },

  {
    key: 'raise-dead',
    name: 'Rappel à la vie',
    level: 5,
    school: 'Nécromancie',
    castingTime: '1 heure',
    range: 'Toucher',
    components: 'V, S, M (un diamant d’une valeur de 500 po, consommé)',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Paladin',
    description: `Vous ramenez à la vie une créature morte depuis peu, avec certaines pénalités.`,
  },

  {
    key: 'rary-s-telepathic-bond',
    name: 'Lien télépathique de Rary',
    level: 5,
    school: 'Divination',
    castingTime: '1 action rituel',
    range: '30 pieds',
    components: 'V, S, M (des morceaux de coquille d’œuf)',
    duration: '1 heure',
    classes: 'Barde, Magicien',
    description: `Vous établissez un lien télépathique entre plusieurs créatures consentantes.`,
  },

  {
    key: 'reincarnate',
    name: 'Réincarnation',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 heure',
    range: 'Toucher',
    components:
      'V, S, M (huiles et onguents rares d’une valeur de 1 000 po, consommés)',
    duration: 'Instantanée',
    classes: 'Druide',
    description: `Vous ramenez une créature morte à la vie dans un nouveau corps.`,
  },

  {
    key: 'scrying',
    name: 'Scrutation',
    level: 5,
    school: 'Divination',
    castingTime: '10 minutes',
    range: 'Personnel',
    components: 'V, S, M (un miroir d’argent)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Clerc, Druide, Magicien',
    description: `Vous observez à distance une créature ou un lieu.`,
  },

  {
    key: 'seeming',
    name: 'Apparence trompeuse',
    level: 5,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: '8 heures',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous modifiez l’apparence de plusieurs créatures à portée.`,
  },

  {
    key: 'summon-dragon',
    name: 'Invocation de dragon',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un objet draconique)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous invoquez un esprit draconique prenant une forme physique.`,
  },

  {
    key: 'telekinesis',
    name: 'Télékinésie',
    level: 5,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Vous manipulez mentalement des créatures ou des objets.`,
  },

  {
    key: 'teleportation-circle',
    name: 'Cercle de téléportation',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 minute',
    range: '10 pieds',
    components: 'V, S, M (craie et encres rares d’une valeur de 50 po)',
    duration: '1 round',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous créez un portail reliant deux cercles de téléportation.`,
  },

  {
    key: 'tree-stride',
    name: 'Marche sylvestre',
    level: 5,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Rôdeur',
    description: `Vous vous déplacez instantanément entre des arbres.`,
  },

  {
    key: 'wall-of-force',
    name: 'Mur de force',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (une pincée de poudre de diamant)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Un mur invisible et indestructible surgit à l’endroit choisi.`,
  },

  {
    key: 'wall-of-stone',
    name: 'Mur de pierre',
    level: 5,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un petit bloc de granit)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Un mur de pierre surgit du sol et peut devenir permanent.`,
  },
];

export async function seedSpellsLevel5(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 5...');

  for (const data of srdSpellsLevel5) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
