import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel3 = [
  {
    key: 'animate-dead',
    name: 'Animation des morts',
    level: 3,
    school: 'Nécromancie',
    castingTime: '1 minute',
    range: '10 pieds',
    components:
      'V, S, M (une goutte de sang, un morceau de chair et une pincée d’os)',
    duration: 'Instantanée',
    classes: 'Clerc, Magicien',
    description: `Ce sort crée un serviteur mort-vivant à partir d’un tas d’os ou d’un cadavre humanoïde de taille Small ou Medium.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 4 ou supérieur, vous animez ou réaffirmez le contrôle d’un mort-vivant supplémentaire par niveau au-delà du niveau 3.`,
  },

  {
    key: 'aura-of-vitality',
    name: 'Aura de vitalité',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `Une aura curative vous entoure. En action bonus à chacun de vos tours, vous pouvez faire regagner 2d6 points de vie à une créature dans l’aura.`,
  },

  {
    key: 'beacon-of-hope',
    name: 'Lueur d’espoir',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc',
    description: `Ce sort confère espoir et vitalité. Les cibles ont Avantage aux jets de sauvegarde de Sagesse et de mort, et regagnent le maximum de points de vie possibles avec les soins.`,
  },

  {
    key: 'bestow-curse',
    name: 'Malédiction',
    level: 3,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Clerc, Paladin',
    description: `Vous touchez une créature et lui imposez une malédiction.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 4 ou supérieur, la durée du sort change selon le niveau d’emplacement utilisé.`,
  },

  {
    key: 'blinding-smite',
    name: 'Châtiment aveuglant',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `La prochaine fois que vous touchez une créature avec une attaque d’arme, elle subit 3d8 dégâts radiants et doit réussir un jet de sauvegarde de Constitution ou être Aveuglée.`,
  },

  {
    key: 'blink',
    name: 'Clignotement',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: '1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `À la fin de chacun de vos tours, vous avez une chance de disparaître dans le Plan Éthéré jusqu’au début de votre prochain tour.`,
  },

  {
    key: 'call-lightning',
    name: 'Appel de la foudre',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Druide',
    description: `Vous invoquez un nuage orageux qui frappe vos ennemis de la foudre.`,
    atHigherLevels: `Les dégâts augmentent de 1d10 pour chaque niveau d’emplacement au-delà du niveau 3.`,
  },

  {
    key: 'clairvoyance',
    name: 'Clairvoyance',
    level: 3,
    school: 'Divination',
    castingTime: '10 minutes',
    range: '1 mile',
    components: 'V, S, M (un focaliseur d’une valeur de 100 po)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Clerc, Magicien',
    description: `Vous créez un capteur invisible dans un lieu familier ou évident que vous pouvez voir à distance.`,
  },

  {
    key: 'conjure-animals',
    name: 'Invocation d’animaux',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Rôdeur',
    description: `Vous invoquez des esprits féeriques prenant la forme de bêtes.`,
    atHigherLevels: `Vous invoquez davantage de créatures lorsque vous lancez ce sort avec un emplacement de sort de niveau supérieur.`,
  },

  {
    key: 'counterspell',
    name: 'Contresort',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 réaction',
    range: '60 pieds',
    components: 'S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous tentez d’interrompre l’incantation d’un sort.`,
  },

  {
    key: 'create-food-and-water',
    name: 'Création de nourriture et d’eau',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Paladin',
    description: `Vous créez de la nourriture et de l’eau suffisantes pour nourrir jusqu’à quinze humanoïdes.`,
  },

  {
    key: 'crusaders-mantle',
    name: 'Manteau du croisé',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `Une aura de puissance divine émane de vous, renforçant les attaques de vos alliés.`,
  },

  {
    key: 'daylight',
    name: 'Lumière du jour',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `Un objet que vous touchez émet une lumière vive dans un rayon de 18 m.`,
  },

  {
    key: 'dispel-magic',
    name: 'Dissipation de la magie',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide, Paladin, Ensorceleur, Magicien',
    description: `Vous mettez fin à des sorts actifs dans la zone.`,
  },
  {
    key: 'fear',
    name: 'Peur',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Personnel (cône de 9 m)',
    components: 'V, S, M (une plume blanche)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Chaque créature dans le cône doit réussir un jet de sauvegarde de Sagesse ou être Effrayée. Une créature effrayée lâche ce qu’elle tient et doit utiliser son action pour fuir.`,
  },

  {
    key: 'fireball',
    name: 'Boule de feu',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: '150 pieds',
    components:
      'V, S, M (une petite boule de guano de chauve-souris et de soufre)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Une explosion de flammes éclate en un point à portée. Chaque créature dans une sphère de 6 m doit réussir un jet de sauvegarde de Dextérité ou subir 8d6 dégâts de Feu.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 3.`,
  },

  {
    key: 'fly',
    name: 'Vol',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une plume d’oiseau)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Vous conférez une vitesse de vol de 18 m à une créature consentante.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 4 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 3.`,
  },

  {
    key: 'gaseous-form',
    name: 'Forme gazeuse',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (un peu de fumée)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous transformez une créature consentante en nuage de brume.`,
  },

  {
    key: 'glyph-of-warding',
    name: 'Symbole de garde',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 heure',
    range: 'Toucher',
    components: 'V, S, M (encens et poudre de diamant d’une valeur de 200 po)',
    duration: 'Jusqu’à dissipation',
    classes: 'Barde, Clerc, Magicien',
    description: `Vous inscrivez un glyphe magique qui se déclenche sous certaines conditions.`,
    atHigherLevels: `Les dégâts ou effets augmentent selon le niveau d’emplacement utilisé.`,
  },

  {
    key: 'haste',
    name: 'Hâte',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (un copeau de racine de réglisse)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous doublez la vitesse de la cible, lui accordez +2 à la CA, Avantage aux jets de Dextérité, et une action supplémentaire à chaque tour.`,
  },

  {
    key: 'hypnotic-pattern',
    name: 'Motif hypnotique',
    level: 3,
    school: 'Illusion',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un bâton lumineux)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Un motif de couleurs fascinantes apparaît et charme les créatures dans la zone.`,
  },

  {
    key: 'lightning-bolt',
    name: 'Éclair',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: '100 pieds',
    components: 'V, S, M (un morceau d’ambre)',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un éclair jaillit de vous dans une ligne, infligeant 8d6 dégâts de Foudre.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 3.`,
  },

  {
    key: 'mass-healing-word',
    name: 'Mot de guérison de groupe',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Clerc',
    description: `Jusqu’à six créatures de votre choix regagnent 1d4 + votre caractéristique d’incantation en points de vie.`,
    atHigherLevels: `Les soins augmentent de 1d4 par niveau d’emplacement au-delà du niveau 3.`,
  },

  {
    key: 'meld-into-stone',
    name: 'Fusion dans la pierre',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: '8 heures',
    classes: 'Clerc, Druide',
    description: `Vous vous fondez dans une surface de pierre suffisamment grande pour vous contenir.`,
  },

  {
    key: 'nondetection',
    name: 'Non-détection',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (poudre de diamant d’une valeur de 25 po)',
    duration: '8 heures',
    classes: 'Barde, Magicien',
    description: `Vous protégez une cible contre les effets de divination.`,
  },

  {
    key: 'phantom-steed',
    name: 'Monture fantomatique',
    level: 3,
    school: 'Illusion',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Magicien',
    description: `Vous créez une monture quasi réelle extrêmement rapide.`,
  },

  {
    key: 'plant-growth',
    name: 'Croissance végétale',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action ou 8 heures',
    range: '150 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Druide, Rôdeur',
    description: `La végétation dans la zone devient dense et difficile à traverser, ou est enrichie pour améliorer les récoltes.`,
  },
  {
    key: 'protection-from-energy',
    name: 'Protection contre l’énergie',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `Vous touchez une créature consentante et lui conférez une résistance à un type de dégâts élémentaires de votre choix.`,
  },

  {
    key: 'remove-curse',
    name: 'Délivrance des malédictions',
    level: 3,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Paladin, Ensorceleur, Magicien',
    description: `À votre toucher, toutes les malédictions affectant une créature ou un objet prennent fin.`,
  },

  {
    key: 'revivify',
    name: 'Rappel à la vie',
    level: 3,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (diamants d’une valeur de 300 po)',
    duration: 'Instantanée',
    classes: 'Clerc, Paladin',
    description: `Vous touchez une créature morte depuis moins d’une minute. Elle revient à la vie avec 1 point de vie.`,
  },

  {
    key: 'sending',
    name: 'Message',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Illimitée',
    components: 'V, S, M (un court fil de cuivre)',
    duration: '1 round',
    classes: 'Barde, Clerc, Ensorceleur, Magicien',
    description: `Vous envoyez un message bref à une créature que vous connaissez, où qu’elle se trouve.`,
  },

  {
    key: 'sleet-storm',
    name: 'Tempête de grêle',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '150 pieds',
    components: 'V, S, M (une pincée de poussière)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Ensorceleur, Magicien',
    description: `Une tempête de pluie verglaçante rend la zone difficile à traverser et perturbe la concentration.`,
  },

  {
    key: 'slow',
    name: 'Lenteur',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (une goutte de mélasse)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Vous altérez le temps autour de créatures, réduisant leur vitesse et limitant leurs actions.`,
  },

  {
    key: 'speak-with-dead',
    name: 'Parler avec les morts',
    level: 3,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '10 pieds',
    components: 'V, S, M (de l’encens)',
    duration: '10 minutes',
    classes: 'Barde, Clerc',
    description: `Vous accordez temporairement la capacité de répondre à des questions à un cadavre.`,
  },

  {
    key: 'spirit-guardians',
    name: 'Gardiens spirituels',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (un symbole sacré)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc',
    description: `Des esprits protecteurs vous entourent et infligent des dégâts aux ennemis proches.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque niveau d’emplacement au-delà du niveau 3.`,
  },

  {
    key: 'stinking-cloud',
    name: 'Nuage nauséabond',
    level: 3,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S, M (un œuf pourri)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Un nuage toxique provoque des haut-le-cœur chez les créatures dans la zone.`,
  },

  {
    key: 'tongues',
    name: 'Langues',
    level: 3,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, M (un petit fragment d’argile)',
    duration: '1 heure',
    classes: 'Barde, Clerc, Ensorceleur, Magicien',
    description: `La créature ciblée peut comprendre et parler toutes les langues.`,
  },

  {
    key: 'wind-wall',
    name: 'Mur de vent',
    level: 3,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S, M (un minuscule ventilateur)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Druide, Rôdeur',
    description: `Un mur de vent fort bloque projectiles et créatures volantes.`,
  },

  {
    key: 'water-breathing',
    name: 'Respiration aquatique',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action rituel',
    range: '30 pieds',
    components: 'V, S, M (un court roseau)',
    duration: '24 heures',
    classes: 'Druide, Rôdeur, Magicien',
    description: `Jusqu’à dix créatures peuvent respirer sous l’eau.`,
  },

  {
    key: 'water-walk',
    name: 'Marche sur l’eau',
    level: 3,
    school: 'Transmutation',
    castingTime: '1 action rituel',
    range: '30 pieds',
    components: 'V, S, M (un morceau de liège)',
    duration: '1 heure',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `Jusqu’à dix créatures peuvent se déplacer sur des surfaces liquides.`,
  },
];

export async function seedSpellsLevel3(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 3...');

  for (const data of srdSpellsLevel3) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
