import { PrismaClient } from '../../../src/generated/prisma/client';

const srdSpellsLevel1 = [
  {
    key: 'alarm',
    name: 'Alarme',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 minute',
    range: '30 pieds',
    components: 'V, S, M (une clochette et un fil d’argent)',
    duration: '8 heures',
    classes: 'Rôdeur, Magicien',
    description: `Vous établissez une alarme contre les intrusions indésirables. Choisissez une porte, une fenêtre ou une zone ne dépassant pas un cube de 6 m de côté à portée. Jusqu’à la fin du sort, une alarme mentale ou sonore se déclenche lorsqu’une créature de taille Tiny ou plus touche ou pénètre dans la zone protégée.`,
  },

  {
    key: 'animal-friendship',
    name: 'Amitié avec les animaux',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (un morceau de nourriture)',
    duration: '24 heures',
    classes: 'Druide, Rôdeur',
    description: `Vous persuadez une bête que vous ne lui voulez aucun mal. Elle doit réussir un jet de sauvegarde de Sagesse ou être charmée par vous pendant la durée du sort.`,
  },

  {
    key: 'armor-of-agathys',
    name: 'Armure d’Agathys',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une coupe d’eau)',
    duration: '1 heure',
    classes: 'Occultiste',
    description: `Une force magique protectrice vous entoure, vous conférant 5 points de vie temporaires. Si une créature vous touche avec une attaque de mêlée tant que vous avez ces points de vie, elle subit 5 dégâts de Froid.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, les points de vie temporaires et les dégâts de Froid augmentent de 5 par niveau au-delà du niveau 1.`,
  },

  {
    key: 'arms-of-hadar',
    name: 'Bras de Hadar',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: 'Personnel (rayon de 3 m)',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Occultiste',
    description: `Des tentacules d’énergie sombre jaillissent de vous. Chaque créature dans un rayon de 3 m doit réussir un jet de sauvegarde de Force ou subir 2d6 dégâts nécrotiques et ne peut pas effectuer de réactions jusqu’à son prochain tour.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'bane',
    name: 'Fléau',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (une goutte de sang)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Clerc',
    description: `Jusqu’à trois créatures de votre choix à portée doivent réussir un jet de sauvegarde de Charisme. En cas d’échec, chaque fois qu’une cible effectue un jet d’attaque ou un jet de sauvegarde avant la fin du sort, elle soustrait 1d4 au résultat.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 1.`,
  },

  {
    key: 'bless',
    name: 'Bénédiction',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (une goutte d’eau bénite)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Clerc, Paladin',
    description: `Vous bénissez jusqu’à trois créatures de votre choix à portée. Chaque fois qu’une cible effectue un jet d’attaque ou un jet de sauvegarde avant la fin du sort, elle peut lancer 1d4 et ajouter le résultat au jet.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, vous pouvez cibler une créature supplémentaire par niveau au-delà du niveau 1.`,
  },

  {
    key: 'burning-hands',
    name: 'Mains brûlantes',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel (cône de 4,5 m)',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Un cône de flammes jaillit de vos mains. Chaque créature dans la zone doit réussir un jet de sauvegarde de Dextérité ou subir 3d6 dégâts de Feu, ou la moitié en cas de réussite.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'charm-person',
    name: 'Charme-personne',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Barde, Druide, Ensorceleur, Magicien',
    description: `Vous tentez de charmer un humanoïde à portée. Il doit réussir un jet de sauvegarde de Sagesse ou être charmé par vous jusqu’à la fin du sort.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, vous pouvez cibler une créature humanoïde supplémentaire par niveau au-delà du niveau 1.`,
  },

  {
    key: 'command',
    name: 'Ordre',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: '1 round',
    classes: 'Clerc, Paladin',
    description: `Vous prononcez un mot de commandement à une créature à portée. Elle doit réussir un jet de sauvegarde de Sagesse ou obéir à l’ordre lors de son prochain tour.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, vous pouvez affecter une créature supplémentaire par niveau au-delà du niveau 1.`,
  },

  {
    key: 'compelled-duel',
    name: 'Duel forcé',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action bonus',
    range: '30 pieds',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `Vous tentez de forcer une créature à vous affronter en duel. Elle doit réussir un jet de sauvegarde de Sagesse ou être attirée vers vous.`,
  },

  {
    key: 'comprehend-languages',
    name: 'Compréhension des langues',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une pincée de suie et de sel)',
    duration: '1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Pendant la durée du sort, vous comprenez le sens littéral de toute langue parlée que vous entendez et de toute langue écrite que vous voyez.`,
  },

  {
    key: 'cure-wounds',
    name: 'Soins',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide, Paladin, Rôdeur',
    description: `Une créature que vous touchez regagne un nombre de points de vie égal à 1d8 + votre caractéristique d’incantation.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, les soins augmentent de 1d8 par niveau au-delà du niveau 1.`,
  },

  {
    key: 'detect-evil-and-good',
    name: 'Détection du bien et du mal',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc, Paladin',
    description: `Pendant la durée du sort, vous savez si des créatures célestes, fiélons, morts-vivants, fées ou élémentaires sont présentes à moins de 9 m de vous.`,
  },

  {
    key: 'detect-magic',
    name: 'Détection de la magie',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Clerc, Druide, Paladin, Rôdeur, Ensorceleur, Magicien',
    description: `Pendant la durée du sort, vous percevez la présence de magie à moins de 9 m de vous.`,
  },

  {
    key: 'detect-poison-and-disease',
    name: 'Détection du poison et des maladies',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc, Druide, Paladin, Rôdeur',
    description: `Pendant la durée du sort, vous pouvez détecter la présence et l’emplacement des poisons, créatures venimeuses et maladies à moins de 9 m de vous.`,
  },

  {
    key: 'disguise-self',
    name: 'Déguisement',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: '1 heure',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous modifiez votre apparence, y compris vos vêtements, armure, armes et autres effets visibles.`,
  },

  {
    key: 'dissonant-whispers',
    name: 'Murmures dissonants',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde',
    description: `Vous murmurez une mélodie discordante qu’une seule créature à portée peut entendre. Elle doit réussir un jet de sauvegarde de Sagesse ou subir 3d6 dégâts psychiques et utiliser immédiatement sa réaction pour s’éloigner de vous.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'divine-favor',
    name: 'Faveur divine',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Paladin',
    description: `Vos attaques d’armes infligent 1d4 dégâts radiants supplémentaires tant que le sort dure.`,
  },
  {
    key: 'ensnaring-strike',
    name: 'Frappe entravante',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Rôdeur',
    description: `La prochaine fois que vous touchez une créature avec une attaque d’arme avant la fin du sort, des lianes magiques surgissent et entravent la cible. Elle doit réussir un jet de sauvegarde de Force ou être Entravée. Une créature entravée subit 1d6 dégâts perforants au début de chacun de ses tours.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'expeditious-retreat',
    name: 'Repli expéditif',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action bonus',
    range: 'Personnel',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Ensorceleur, Magicien',
    description: `Ce sort vous permet de faire l’action Dash en action bonus à chacun de vos tours jusqu’à la fin du sort.`,
  },

  {
    key: 'faerie-fire',
    name: 'Lueur féerique',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Druide',
    description: `Chaque objet et créature dans un cube de 6 m de côté à portée est entouré d’une lumière colorée. Les créatures affectées ne peuvent pas devenir Invisibles et les attaques contre elles ont Avantage.`,
  },

  {
    key: 'false-life',
    name: 'Fausse vie',
    level: 1,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S, M (une petite quantité d’alcool)',
    duration: '1 heure',
    classes: 'Ensorceleur, Magicien',
    description: `Vous gagnez 1d4 + 4 points de vie temporaires pour la durée du sort.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 2 ou supérieur, vous gagnez 5 points de vie temporaires supplémentaires par niveau au-delà du niveau 1.`,
  },

  {
    key: 'feather-fall',
    name: 'Chute de plume',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 réaction',
    range: '60 pieds',
    components: 'V, M (une plume)',
    duration: '1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Choisissez jusqu’à cinq créatures à portée qui chutent. Leur vitesse de chute ralentit à 18 m par round jusqu’à la fin du sort.`,
  },

  {
    key: 'find-familiar',
    name: 'Appel de familier',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 heure',
    range: '10 pieds',
    components: 'V, S, M (charbon, encens et herbes d’une valeur de 10 po)',
    duration: 'Instantanée',
    classes: 'Magicien',
    description: `Vous invoquez un esprit prenant la forme d’un animal familier qui vous obéit et agit indépendamment.`,
  },

  {
    key: 'fog-cloud',
    name: 'Nuage de brouillard',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Druide, Rôdeur, Ensorceleur, Magicien',
    description: `Vous créez une sphère de brouillard de 6 m de rayon centrée sur un point à portée. La zone est lourdement obscurcie.`,
    atHigherLevels: `Le rayon de la sphère augmente de 6 m pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'goodberry',
    name: 'Baies nourricières',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une branche de gui)',
    duration: 'Instantanée',
    classes: 'Druide, Rôdeur',
    description: `Jusqu’à dix baies apparaissent dans votre main. Une créature peut utiliser son action pour manger une baie et regagner 1 point de vie. Une baie fournit suffisamment de nourriture pour une journée.`,
  },

  {
    key: 'grease',
    name: 'Graisse',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un peu de graisse de porc)',
    duration: '1 minute',
    classes: 'Ensorceleur, Magicien',
    description: `Une surface glissante de 3 m de côté apparaît à portée. Les créatures dans la zone doivent réussir un jet de sauvegarde de Dextérité ou tomber à terre.`,
  },

  {
    key: 'guiding-bolt',
    name: 'Trait guidé',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: '1 round',
    classes: 'Clerc',
    description: `Faites une attaque de sort à distance contre une créature. En cas de réussite, elle subit 4d6 dégâts radiants et la prochaine attaque contre elle avant la fin de votre prochain tour a Avantage.`,
    atHigherLevels: `Les dégâts augmentent de 1d6 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'healing-word',
    name: 'Mot de guérison',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action bonus',
    range: '60 pieds',
    components: 'V',
    duration: 'Instantanée',
    classes: 'Barde, Clerc, Druide',
    description: `Une créature de votre choix à portée regagne un nombre de points de vie égal à 1d4 + votre caractéristique d’incantation.`,
    atHigherLevels: `Les soins augmentent de 1d4 par niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'hellish-rebuke',
    name: 'Réprimande infernale',
    level: 1,
    school: 'Évocation',
    castingTime: '1 réaction',
    range: '60 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Occultiste',
    description: `En réaction lorsque vous subissez des dégâts, vous entourez votre agresseur de flammes infernales. Il doit réussir un jet de sauvegarde de Dextérité ou subir 2d10 dégâts de Feu.`,
    atHigherLevels: `Les dégâts augmentent de 1d10 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'heroism',
    name: 'Héroïsme',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Barde, Paladin',
    description: `Une créature consentante devient immunisée contre la condition Effrayé et gagne des points de vie temporaires égaux à votre caractéristique d’incantation au début de chacun de ses tours.`,
  },

  {
    key: 'hex',
    name: 'Maléfice',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action bonus',
    range: '90 pieds',
    components: 'V, S, M (l’œil pétrifié d’un triton)',
    duration: 'Concentration, jusqu’à 1 heure',
    classes: 'Occultiste',
    description: `Vous maudissez une créature à portée. Jusqu’à la fin du sort, vous infligez 1d6 dégâts nécrotiques supplémentaires chaque fois que vous la touchez avec une attaque.`,
    atHigherLevels: `Lorsque vous lancez ce sort avec un emplacement de sort de niveau 3 ou supérieur, la durée du sort augmente.`,
  },

  {
    key: 'identify',
    name: 'Identification',
    level: 1,
    school: 'Divination',
    castingTime: '1 minute',
    range: 'Toucher',
    components: 'V, S, M (une perle d’une valeur de 100 po)',
    duration: 'Instantanée',
    classes: 'Barde, Magicien',
    description: `Vous découvrez les propriétés magiques d’un objet ou d’un effet magique que vous touchez.`,
  },

  {
    key: 'illusory-script',
    name: 'Écriture illusoire',
    level: 1,
    school: 'Illusion',
    castingTime: '1 minute',
    range: 'Toucher',
    components: 'S, M (encre à base de plomb)',
    duration: '10 jours',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous écrivez sur un parchemin et cachez le véritable message derrière une illusion.`,
  },

  {
    key: 'jump',
    name: 'Saut',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une patte de grenouille)',
    duration: '1 minute',
    classes: 'Druide, Rôdeur, Ensorceleur, Magicien',
    description: `La distance de saut de la cible est triplée pendant la durée du sort.`,
  },
  {
    key: 'longstrider',
    name: 'Marche sur la longue distance',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (une pincée de terre)',
    duration: '1 heure',
    classes: 'Barde, Druide, Rôdeur, Ensorceleur, Magicien',
    description: `La vitesse de déplacement de la cible augmente de 3 m pendant la durée du sort.`,
  },

  {
    key: 'mage-armor',
    name: 'Armure du mage',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (un morceau de cuir tanné)',
    duration: '8 heures',
    classes: 'Ensorceleur, Magicien',
    description: `Une créature consentante qui ne porte pas d’armure voit sa CA de base devenir 13 + son modificateur de Dextérité pendant la durée du sort.`,
  },

  {
    key: 'magic-missile',
    name: 'Projectile magique',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: '120 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Ensorceleur, Magicien',
    description: `Vous créez trois projectiles de force magique. Chaque projectile touche automatiquement une créature de votre choix et inflige 1d4 + 1 dégâts de Force.`,
    atHigherLevels: `Vous créez un projectile supplémentaire pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'protection-from-evil-and-good',
    name: 'Protection contre le bien et le mal',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Toucher',
    components: 'V, S, M (eau bénite ou poudre d’argent)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Clerc, Paladin, Rôdeur, Occultiste',
    description: `Jusqu’à la fin du sort, une créature consentante est protégée contre certains types de créatures, qui ont Désavantage aux jets d’attaque contre elle.`,
  },

  {
    key: 'purify-food-and-drink',
    name: 'Purification de nourriture et boisson',
    level: 1,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '10 pieds',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Clerc, Druide, Paladin',
    description: `Toute nourriture et boisson non magiques dans une sphère de 1,5 m de rayon sont purifiées et rendues exemptes de poison et de maladie.`,
  },

  {
    key: 'ray-of-sickness',
    name: 'Rayon maladif',
    level: 1,
    school: 'Nécromancie',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S',
    duration: '1 round',
    classes: 'Ensorceleur, Occultiste',
    description: `Faites une attaque de sort à distance. En cas de réussite, la cible subit 2d8 dégâts de Poison et doit réussir un jet de sauvegarde de Constitution ou être Empoisonnée jusqu’à la fin de votre prochain tour.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'sanctuary',
    name: 'Sanctuaire',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action bonus',
    range: '30 pieds',
    components: 'V, S, M (un petit miroir d’argent)',
    duration: '1 minute',
    classes: 'Clerc',
    description: `Vous protégez une créature contre les attaques. Toute créature qui tente d’attaquer la cible doit d’abord réussir un jet de sauvegarde de Sagesse.`,
  },

  {
    key: 'shield',
    name: 'Bouclier',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 réaction',
    range: 'Personnel',
    components: 'V, S',
    duration: '1 round',
    classes: 'Ensorceleur, Magicien',
    description: `Une barrière invisible vous protège. Jusqu’au début de votre prochain tour, vous gagnez +5 à la CA, y compris contre l’attaque déclenchante.`,
  },

  {
    key: 'silent-image',
    name: 'Image silencieuse',
    level: 1,
    school: 'Illusion',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un morceau de laine)',
    duration: 'Concentration, jusqu’à 10 minutes',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Vous créez l’image d’un objet, d’une créature ou d’un phénomène visible qui n’émet ni son ni odeur.`,
  },

  {
    key: 'sleep',
    name: 'Sommeil',
    level: 1,
    school: 'Enchantement',
    castingTime: '1 action',
    range: '90 pieds',
    components: 'V, S, M (une pincée de sable fin)',
    duration: '1 minute',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Ce sort plonge des créatures dans un sommeil magique. Il affecte d’abord les créatures ayant le moins de points de vie.`,
    atHigherLevels: `Les points de vie affectés augmentent de 2d8 par niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'speak-with-animals',
    name: 'Parler avec les animaux',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Personnel',
    components: 'V, S',
    duration: '10 minutes',
    classes: 'Barde, Druide, Rôdeur',
    description: `Pendant la durée du sort, vous pouvez comprendre et communiquer verbalement avec les bêtes.`,
  },

  {
    key: 'thunderwave',
    name: 'Vague tonnante',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: 'Personnel (cube de 4,5 m)',
    components: 'V, S',
    duration: 'Instantanée',
    classes: 'Barde, Ensorceleur, Magicien',
    description: `Une onde de force tonnante se propage depuis vous. Les créatures dans la zone subissent 2d8 dégâts de Tonnerre et sont repoussées.`,
    atHigherLevels: `Les dégâts augmentent de 1d8 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },

  {
    key: 'unseen-servant',
    name: 'Serviteur invisible',
    level: 1,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 pieds',
    components: 'V, S, M (un fil et un morceau de bois)',
    duration: '1 heure',
    classes: 'Barde, Magicien',
    description: `Ce sort crée une force invisible qui exécute des tâches simples à votre place.`,
  },

  {
    key: 'witch-bolt',
    name: 'Éclair de sorcière',
    level: 1,
    school: 'Évocation',
    castingTime: '1 action',
    range: '30 pieds',
    components: 'V, S, M (une brindille de bois frappée par la foudre)',
    duration: 'Concentration, jusqu’à 1 minute',
    classes: 'Ensorceleur, Occultiste, Magicien',
    description: `Un éclair relie votre main à une créature. Faites une attaque de sort à distance. En cas de réussite, la cible subit 1d12 dégâts de Foudre.`,
    atHigherLevels: `Les dégâts augmentent de 1d12 pour chaque niveau d’emplacement au-delà du niveau 1.`,
  },
];

export async function seedSpellsLevel1(prisma: PrismaClient) {
  console.log('🌱 Seeding SRD spells — level 1...');

  for (const data of srdSpellsLevel1) {
    await prisma.spell.upsert({
      where: { key: data.key },
      update: {
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
      create: {
        key: data.key,
        name: data.name,
        level: data.level,
        school: data.school,
        castingTime: data.castingTime,
        range: data.range,
        components: data.components,
        duration: data.duration,
        classes: data.classes,
        description: data.description,
        atHigherLevels: data.atHigherLevels,
      },
    });

    console.log(`  ✅ Spell upserted: ${data.key}`);
  }
}
